# Generated by Django 3.0.3 on 2020-11-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterchecks_app', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, upload_to='user_files'),
        ),
    ]
