# Generated by Django 3.0.3 on 2020-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterchecks_app', '0005_auto_20201101_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='courseenquiry',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
