# Generated by Django 3.0.3 on 2020-10-28 22:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('betterchecks_app', '0002_auto_20201027_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('organization', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
