# Generated by Django 3.0.3 on 2020-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterchecks_app', '0003_auto_20201028_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
